In [1]:
import pandas as pd
import numpy as np
import os

from ddf_utils.str import to_concept_id
from ddf_utils.index import create_index_file

In [2]:
source = 'source/CPI 2015_data.xlsx'

In [3]:
data = pd.read_excel(source)

In [4]:
data

,Rank,CPI2015,Country,Region,wbcode,World Bank CPIA,World Economic Forum EOS,Bertelsmann Foundation TI,African Dev Bank,IMD World Competitiveness Yearbook,...,CPI2015(2),Rank2,Number of Sources,Std Deviation of Sources,Standard Error,Minimum,Maximum,Lower CI,Upper CI,Country2
0,1,91,Denmark,WE/EU,DNK,NaN,89.0,NaN,NaN,96.0,...,91,1,7,5.71,2.16,83,98,87.4360,94.5640,Denmark
1,2,90,Finland,WE/EU,FIN,NaN,93.0,NaN,NaN,91.0,...,90,2,7,4.69,1.77,83,98,87.0795,92.9205,Finland
2,3,89,Sweden,WE/EU,SWE,NaN,89.0,NaN,NaN,87.0,...,89,3,7,4.53,1.71,83,98,86.1785,91.8215,Sweden
3,4,88,New Zealand,AP,NZL,NaN,92.0,NaN,NaN,93.0,...,88,4,7,6.32,2.39,81,98,84.0565,91.9435,New Zealand
4,5,87,Netherlands,WE/EU,NLD,NaN,84.0,NaN,NaN,85.0,...,87,5,7,4.79,1.81,83,97,84.0135,89.9865,Netherlands
5,5,87,Norway,WE/EU,NOR,NaN,92.0,NaN,NaN,84.0,...,87,5,7,7.93,3.00,73,98,82.0500,91.9500,Norway
6,7,86,Switzerland,WE/EU,CHE,NaN,87.0,NaN,NaN,88.0,...,86,7,6,6.25,2.55,73,89,81.7925,90.2075,Switzerland
7,8,85,Singapore,AP,SGP,NaN,92.0,75.0,NaN,87.0,...,85,8,8,5.70,2.02,75,92,81.6670,88.3330,Singapore
8,9,83,Canada,AME,CAN,NaN,79.0,NaN,NaN,79.0,...,83,9,7,4.31,1.63,79,89,80.3105,85.6895,Canada
9,10,81,Germany,WE/EU,DEU,NaN,72.0,NaN,NaN,83.0,...,81,10,7,6.62,2.50,72,89,76.8750,85.1250,Germany
10,10,81,Luxembourg,WE/EU,LUX,NaN,89.0,NaN,NaN,85.0,...,81,10,5,13.45,6.02,57,89,71.0670,90.9330,Luxembourg
11,10,81,United Kingdom,WE/EU,GBR,NaN,82.0,NaN,NaN,81.0,...,81,10,7,6.36,2.40,73,89,77.0400,84.9600,United Kingdom
12,13,79,Australia,AP,AUS,NaN,81.0,NaN,NaN,82.0,...,79,13,8,4.24,1.50,71,83,76.5250,81.4750,Australia
13,13,79,Iceland,WE/EU,ISL,NaN,87.0,NaN,NaN,83.0,...,79,13,5,10.14,4.53,65,89,71.5255,86.4745,Iceland
14,15,77,Belgium,WE/EU,BEL,NaN,79.0,NaN,NaN,77.0,...,77,15,7,3.55,1.34,71,81,74.7890,79.2110,Belgium
15,16,76,Austria,WE/EU,AUT,NaN,77.0,NaN,NaN,70.0,...,76,16,7,4.65,1.76,70,81,73.0960,78.9040,Austria
16,16,76,The United States Of America,AME,USA,NaN,69.0,NaN,NaN,74.0,...,76,16,8,9.83,3.48,59,89,70.2580,81.7420,The United States Of America
17,18,75,Hong Kong,AP,HKG,NaN,87.0,NaN,NaN,80.0,...,75,18,7,6.55,2.48,69,87,70.9080,79.0920,Hong Kong
18,18,75,Ireland,WE/EU,IRL,NaN,89.0,NaN,NaN,83.0,...,75,18,6,12.04,4.92,54,89,66.8820,83.1180,Ireland
19,18,75,Japan,AP,JPN,NaN,84.0,NaN,NaN,76.0,...,75,18,8,8.38,2.96,57,84,70.1160,79.8840,Japan
20,21,74,Uruguay,AME,URY,NaN,71.0,79.0,NaN,NaN,...,74,21,6,4.12,1.68,70,79,71.2280,76.7720,Uruguay
21,22,71,Qatar,MENA,QAT,NaN,83.0,40.0,NaN,79.0,...,71,22,6,16.23,6.63,40,83,60.0605,81.9395,Qatar
22,23,70,Chile,AME,CHL,NaN,66.0,75.0,NaN,60.0,...,70,23,8,6.09,2.15,60,79,66.4525,73.5475,Chile
23,23,70,Estonia,WE/EU,EST,NaN,79.0,75.0,NaN,73.0,...,70,23,9,8.36,2.79,54,81,65.3965,74.6035,Estonia
24,23,70,France,WE/EU,FRA,NaN,70.0,NaN,NaN,71.0,...,70,23,7,6.60,2.49,57,79,65.8915,74.1085,France
25,23,70,United Arab Emirates,MENA,ARE,NaN,91.0,53.0,NaN,76.0,...,70,23,7,13.41,5.07,53,91,61.6345,78.3655,United Arab Emirates
26,27,65,Bhutan,AP,BTN,70.0,60.0,66.0,NaN,NaN,...,65,27,4,4.27,2.14,60,70,61.4690,68.5310,Bhutan
27,28,63,Botswana,SSA,BWA,NaN,59.0,58.0,NaN,NaN,...,63,28,6,5.76,2.35,58,71,59.1225,66.8775,Botswana
28,28,63,Portugal,WE/EU,PRT,NaN,62.0,NaN,NaN,58.0,...,63,28,7,7.12,2.69,54,73,58.5615,67.4385,Portugal
29,30,62,Poland,WE/EU,POL,NaN,58.0,71.0,NaN,58.0,...,62,30,9,6.93,2.31,54,73,58.1885,65.8115,Poland
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,139,25,Bangladesh,AP,BGD,23.0,19.0,23.0,NaN,NaN,...,25,139,7,11.36,4.29,16,50,17.9215,32.0785,Bangladesh
139,139,25,Guinea,SSA,GIN,23.0,15.0,36.0,32.0,NaN,...,25,139,6,7.73,3.16,15,36,19.7860,30.2140,Guinea
140,139,25,Kenya,SSA,KEN,35.0,30.0,28.0,35.0,NaN,...,25,139,8,8.54,3.02,11,35,20.0170,29.9830,Kenya
141,139,25,Laos,AP,LAO,23.0,40.0,15.0,NaN,NaN,...,25,139,4,10.61,5.31,15,40,16.2385,33.7615,Laos
142,139,25,Papua New Guinea,AP,PNG,35.0,NaN,28.0,NaN,NaN,...,25,139,5,9.44,4.22,11,35,18.0370,31.9630,Papua New Guinea
143,139,25,Uganda,SSA,UGA,12.0,28.0,32.0,32.0,NaN,...,25,139,8,9.02,3.19,12,38,19.7365,30.2635,Uganda
144,145,24,Central African Republic,SSA,CAF,23.0,NaN,28.0,22.0,NaN,...,24,145,4,2.87,1.44,22,28,21.6240,26.3760,Central African Republic
145,146,23,Congo Republic,SSA,COG,12.0,NaN,19.0,42.0,NaN,...,23,146,6,10.07,4.11,12,42,16.2185,29.7815,Republic of Congo
146,147,22,Chad,SSA,TCD,23.0,16.0,19.0,30.0,NaN,...,22,147,5,5.24,2.34,16,30,18.1390,25.8610,Chad
147,147,22,Democratic Republic of the Congo,SSA,COD,12.0,NaN,19.0,37.0,NaN,...,22,147,6,8.20,3.35,12,37,16.4725,27.5275,The Democratic Republic of Congo
148,147,22,Myanmar,AP,MMR,35.0,27.0,19.0,NaN,NaN,...,22,147,7,7.47,2.82,11,35,17.3470,26.6530,Myanmar
149,150,21,Burundi,SSA,BDI,23.0,28.0,19.0,25.0,NaN,...,21,150,5,6.57,2.94,11,28,16.1490,25.8510,Burundi
150,150,21,Cambodia,AP,KHM,12.0,35.0,15.0,NaN,NaN,...,21,150,7,10.24,3.87,10,35,14.6145,27.3855,Cambodia
151,150,21,Zimbabwe,SSA,ZWE,0.0,38.0,15.0,17.0,NaN,...,21,150,8,12.85,4.54,0,38,13.5090,28.4910,Zimbabwe
152,153,19,Uzbekistan,ECA,UZB,12.0,NaN,19.0,NaN,NaN,...,19,153,6,6.65,2.71,11,29,14.5285,23.4715,Uzbekistan
153,154,18,Eritrea,SSA,ERI,12.0,NaN,10.0,7.0,NaN,...,18,154,4,16.30,8.15,7,42,4.5525,31.4475,Eritrea
154,154,18,Syria,MENA,SYR,NaN,NaN,6.0,NaN,NaN,...,18,154,4,11.32,5.66,6,32,8.6610,27.3390,Syria
155,154,18,Turkmenistan,ECA,TKM,NaN,NaN,19.0,NaN,NaN,...,18,154,4,4.76,2.38,11,21,14.0730,21.9270,Turkmenistan
156,154,18,Yemen,MENA,YEM,12.0,14.0,28.0,NaN,NaN,...,18,154,6,6.52,2.66,12,28,13.6110,22.3890,Yemen
157,158,17,Haiti,AME,HTI,23.0,24.0,15.0,NaN,NaN,...,17,158,5,6.12,2.74,11,24,12.4790,21.5210,Haiti
158,158,17,Guinea-Bissau,SSA,GNB,12.0,NaN,NaN,20.0,NaN,...,17,158,4,5.26,2.63,12,22,12.6605,21.3395,Guinea-Bissau
159,158,17,Venezuela,AME,VEN,NaN,21.0,15.0,NaN,25.0,...,17,158,7,6.99,2.64,5,25,12.6440,21.3560,Venezuela
160,161,16,Iraq,MENA,IRQ,NaN,NaN,19.0,NaN,NaN,...,16,161,4,4.99,2.50,11,21,11.8750,20.1250,Iraq
161,161,16,Libya,MENA,LBY,NaN,26.0,10.0,NaN,NaN,...,16,161,5,7.11,3.18,10,26,10.7530,21.2470,Libya
162,163,15,Angola,SSA,AGO,NaN,17.0,15.0,NaN,NaN,...,15,163,5,4.02,1.80,11,21,12.0300,17.9700,Angola
163,163,15,South Sudan,SSA,NaN,12.0,NaN,15.0,17.0,NaN,...,15,163,3,2.52,1.45,12,17,12.6075,17.3925,South Sudan
164,165,12,Sudan,MENA,SDN,0.0,NaN,15.0,20.0,NaN,...,12,165,6,8.92,3.64,0,21,5.9940,18.0060,Sudan
165,166,11,Afghanistan,AP,AFG,12.0,NaN,19.0,NaN,NaN,...,11,166,4,6.98,3.49,2,19,5.2415,16.7585,Afghanistan
166,167,8,Korea (North),AP,PRK,NaN,NaN,10.0,NaN,NaN,...,8,167,3,5.86,3.38,1,12,2.4230,13.5770,North Korea
167,167,8,Somalia,SSA,SOM,NaN,NaN,6.0,2.0,NaN,...,8,167,4,4.65,2.33,2,12,4.1555,11.8445,Somalia

In [5]:
data.columns

Index(['Rank', 'CPI2015', 'Country', 'Region', 'wbcode', 'World Bank CPIA',
       'World Economic Forum EOS', 'Bertelsmann Foundation TI',
       'African Dev Bank', 'IMD World Competitiveness Yearbook',
       'Bertelsmann Foundation SGI', 'World Justice Project ROL',
       'PRS International Country Risk Guide', 'Economist Intelligence Unit',
       'IHS Global Insight', 'PERC Asia Risk Guide', 'Freedom House NIT',
       'CPI2015(2)', 'Rank2', 'Number of Sources', 'Std Deviation of Sources',
       'Standard Error', 'Minimum', 'Maximum', 'Lower CI', 'Upper CI',
       'Country2'],
      dtype='object')

In [13]:
all_data = {}

for f in os.listdir('source/'):
    if 'xls' in f:
        if '2014' in f:
            data = pd.read_excel(os.path.join('source', f), skiprows=1)
            data = data[['Country / Territory', 'Unnamed: 2', 'CPI 2014 Score']]  ## unnamed 2 is wbcode
            data['year'] = 2014
            all_data['2014'] = data
        if '2015' in f:
            data = pd.read_excel(os.path.join('source', f))
            data = data[['Country', 'wbcode', 'CPI2015']]
            data['year'] = 2015
            all_data['2015'] = data
        if '2010' in f:
            data = pd.read_excel(os.path.join('source', f), skiprows=1)
            data = data[['Country / Territory', 'CPI 2010 Score']]
            data['year'] = 2010
            all_data['2010'] = data
        if '2011' in f:
            data = pd.read_excel(os.path.join('source', f))
            data = data[['country', 'cpi11']]
            data['year'] = 2011
            all_data['2011'] = data
        if '2012' in f:
            data = pd.read_excel(os.path.join('source', f))
            data = data[['Country / Territory', 'CPI 2012 Score']]
            data['year'] = 2012
            all_data['2012'] = data
        if '2013' in f:
            data = pd.read_excel(os.path.join('source', f))
            data = data[['Country / Territory', 'Unnamed: 2', 'CPI 2013 Score']]  ## unnamed 2 is wbcode
            data['year'] = 2013
            all_data['2013'] = data

In [16]:
all_data['2014'] = all_data['2014'].dropna()

all_data['2014'].columns = ['country', 'wbcode', 'cpi', 'year']

In [19]:
all_data['2013'] = all_data['2013'].dropna()

all_data['2013'].columns = ['country', 'wbcode', 'cpi', 'year']

In [21]:
all_data['2012'] = all_data['2012'].dropna()

all_data['2012'].columns = ['country', 'cpi', 'year']

In [25]:
all_data['2011'] = all_data['2011'].dropna()

all_data['2011'].columns = ['country', 'cpi', 'year']

In [27]:
all_data['2010'] = all_data['2010'].drop([0, 1]).dropna()

all_data['2010'].columns = ['country', 'cpi', 'year']

In [30]:
all_data['2015'] = all_data['2015'].dropna()

all_data['2015'].columns = ['country', 'wbcode', 'cpi', 'year']

In [80]:
all_data_df = pd.concat(all_data.values())

In [81]:
all_data_df = all_data_df.reset_index(drop=True)

In [82]:
gps = all_data_df.groupby('country')

In [83]:
for k, v in gps.groups.items():
    
    df = all_data_df[all_data_df['country'] == k]
    
    wbcode_list = df['wbcode'].unique()
    wbcode_list = [x for x in wbcode_list if x is not np.nan]
    
    if len(wbcode_list) == 0:
        country = to_concept_id(k)
        
    else:
        country = wbcode_list[0]
        
    all_data_df.loc[v, 'wbcode'] = country

In [84]:
all_data_df.query('country == "South Korea"')

         country      cpi       wbcode  year
914  South Korea  5.44408  south_korea  2011

In [85]:
all_data_df

                           country       cpi                     wbcode  year
0                          Denmark        91                        DNK  2015
1                          Finland        90                        FIN  2015
2                           Sweden        89                        SWE  2015
3                      New Zealand        88                        NZL  2015
4                      Netherlands        87                        NLD  2015
5                           Norway        87                        NOR  2015
6                      Switzerland        86                        CHE  2015
7                        Singapore        85                        SGP  2015
8                           Canada        83                        CAN  2015
9                          Germany        81                        DEU  2015
10                      Luxembourg        81                        LUX  2015
11                  United Kingdom        81                        GBR  2015
12                       Australia        79                        AUS  2015
13                         Iceland        79                        ISL  2015
14                         Belgium        77                        BEL  2015
15                         Austria        76                        AUT  2015
16    The United States Of America        76                        USA  2015
17                       Hong Kong        75                        HKG  2015
18                         Ireland        75                        IRL  2015
19                           Japan        75                        JPN  2015
20                         Uruguay        74                        URY  2015
21                           Qatar        71                        QAT  2015
22                           Chile        70                        CHL  2015
23                         Estonia        70                        EST  2015
24                          France        70                        FRA  2015
25            United Arab Emirates        70                        ARE  2015
26                          Bhutan        65                        BTN  2015
27                        Botswana        63                        BWA  2015
28                        Portugal        63                        PRT  2015
29                          Poland        62                        POL  2015
...                            ...       ...                        ...   ...
1025                    Kyrgyzstan   2.28823                        KGZ  2011
1026                    Tajikistan   2.24678                        TJK  2011
1027                 Côte d´Ivoire   2.21659                        CIV  2011
1028                      Paraguay   2.21601                        PRY  2011
1029                         Nepal   2.20405                        NPL  2011
1030                      Cambodia   2.20049                        KHM  2011
1031                      Zimbabwe   2.17283                        ZWE  2011
1032                          Laos   2.14566                        LAO  2011
1033      Central African Republic   2.14174                        CAF  2011
1034                 Guinea-Bissau   2.13343                        GNB  2011
1035                         Yemen   2.12721                        YEM  2011
1036              Papua New Guinea   2.09804                        PNG  2011
1037               Congo  Republic   2.08648             congo_republic  2011
1038                        Guinea   2.04298                        GIN  2011
1039                          Chad   2.02989                        TCD  2011
1040                        Angola   1.99595                        AGO  2011
1041                     Venezuela   1.99133                        VEN  2011
1042                       Burundi   1.95947                        BDI  2011
1043     Congo Democratic Republic   1.95462  congo_democratic_republic  2011
1044                         Libya   1.94844                        LBY  2011
1045             Equatorial Guinea     1.847                        GNQ  2011
1046                         Haiti   1.81348                        HTI  2011
1047                          Iraq   1.74055                        IRQ  2011
1048                    Uzbekistan   1.56402                        UZB  2011
1049                  Turkmenistan   1.54282                        TKM  2011
1050                         Sudan   1.50407                        SDN  2011
1051                   Afghanistan   1.45829                        AFG  2011
1052                       Myanmar   1.43394                        MMR  2011
1053                       Somalia   1.06124                        SOM  2011
1054                   North Korea  0.963864                north_korea  2011

[1055 rows x 4 columns]

In [86]:
# country

In [88]:
country = all_data_df[['country', 'wbcode']].copy()

In [89]:
country.columns = ['name', 'country']

In [90]:
country['country'] = country['country'].map(to_concept_id)

In [91]:
country[['country', 'name']].drop_duplicates().to_csv('../ddf--entities--country.csv', index=False)

In [92]:
# concept

concepts = [['name', 'Name', 'string'], ['year', 'Year', 'time'],
            ['country', 'Country / Territory', 'entity_domain'],
            ['cpi', 'Corruption Perceptions Index', 'measure']
           ]

In [93]:
conc_df = pd.DataFrame(concepts, columns=['concept', 'name', 'concept_type'])

In [94]:
conc_df.to_csv('../ddf--concepts.csv', index=False)

In [95]:
# dps

In [97]:
dps = all_data_df[['wbcode', 'year', 'cpi']].copy()

dps.columns = ['country', 'year', 'cpi']

In [ ]:
dps['conuntry'] = dps['country'].map(to_concept_id)

In [ ]:
dps.to_csv('../ddf--datapoints--cpi--by--country--year.csv', index=False)